version: "3.9"
services:
  department: 
    container_name: dept_service
    build: 
      context: ./dept-service
      dockerfile: Dockerfile
    ports:
      - 8081:8081
  user:
    container_name: user_service
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    environment:
      - "ecominds.endpoint.dept-service.base-path=http://department:8081/api/departments/"
    depends_on:
      - department